import { LessonDetail } from '@/sanity/types'

export const DEMO_LESSONS: Record<string, LessonDetail> = {
  'card-anatomy': {
    _id: 'demo-card-anatomy',
    _type: 'lesson',
    title: 'Card Anatomy',
    slug: { current: 'card-anatomy' },
    category: 'foundations',
    level: 'complete-beginner',
    tagline: 'Know your weapon before you learn to wield it.',
    overview: 'Every playing card is a carefully engineered object. Before you can manipulate a deck, you need to understand exactly what you\'re holding. Magicians who understand card anatomy spot opportunities that others miss — and they never get caught off guard by a card that behaves unexpectedly.',
    estimatedTime: 5,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'The Face and Back',
        instruction: 'Hold a card face-up. The face is the printed side showing suit and value. The back features a pattern — usually bicycle or similar — that looks identical across all 52 cards. This uniformity is what makes deception possible.',
        cardAnimation: 'reveal',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Indices',
        instruction: 'Look at the top-left and bottom-right corners. These small printed symbols show the card\'s value (A, 2-10, J, Q, K) and suit (♠ ♥ ♦ ♣). They appear twice so the card is readable when held in a fan. A magician uses these to secretly identify a card without showing its face.',
        fingerNote: 'When fanning cards toward a spectator, control the spread so only the indices of one specific card are visible at a time.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Pips and Face Cards',
        instruction: 'Number cards (2-10) show pip symbols — the large suit symbols arranged in a pattern matching their count. Face cards (Jack, Queen, King) show illustrated figures. The Ace is unique — it bears a single large pip in the center and is traditionally the most decorated card in the deck.',
      },
      {
        _key: 's4',
        stepNumber: 4,
        title: 'The White Border',
        instruction: 'Every card has a narrow white border around the printed design. This border is critical: it makes the deck appear perfectly squared when viewed from the side. Tiny misalignments at the border are what get magicians caught during cuts and controls.',
        fingerNote: 'When performing controls, always maintain perfect border alignment. Even a 1mm offset is visible to a sharp-eyed spectator.',
        cardAnimation: 'none',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Ignoring card condition',
        fix: 'Always perform with a new or near-new deck. Bent, worn, or marked cards break the illusion before you\'ve done a single move.',
      },
      {
        _key: 'm2',
        mistake: 'Not knowing which cards are which by feel',
        fix: 'Practice identifying cards by feel alone — face cards are slightly stiffer, and after handling, you\'ll develop sensitivity to deck position.',
      },
    ],
    practiceDrill: {
      title: 'Blind Sort',
      description: 'Without looking, sort a shuffled deck into face cards and number cards by touch alone. Focus on the stiffness difference between face cards and pips.',
      reps: '3 × full deck, daily for one week',
    },
    performanceContext: 'Card anatomy knowledge rarely appears directly in performance — but it\'s the foundation everything else is built on. When you can feel a break, spot an index, or detect a subtle crimp, you\'ll understand exactly why those skills matter.',
  },

  'how-to-hold-a-deck': {
    _id: 'demo-hold-deck',
    _type: 'lesson',
    title: 'How to Hold a Deck',
    slug: { current: 'how-to-hold-a-deck' },
    category: 'foundations',
    level: 'complete-beginner',
    tagline: 'Your grip is your technique. Everything flows from here.',
    overview: 'The way you hold a deck determines every move you can make with it. Three grips dominate card magic: dealer\'s grip for dealing and spreading, mechanic\'s grip for controls and forces, and biddle grip for specific steals and moves. You\'ll use all three constantly.',
    estimatedTime: 8,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Dealer\'s Grip',
        instruction: 'Hold the deck in your left hand. The deck rests across your four fingers, which curl up along the right long edge. Your thumb rests along the left long edge. The deck is roughly horizontal. This is the starting position for almost every deal, shuffle, and spread.',
        cardAnimation: 'fan',
        fingerNote: 'Your index finger curls slightly against the front short edge. This gives you control of the deck\'s forward motion during deals.',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'Mechanic\'s Grip',
        instruction: 'Similar to dealer\'s grip, but your index finger extends along the front short edge of the deck. This grip gives you much finer control — you can feel every card, hold breaks easily, and execute cuts with precision. Most serious card workers prefer this for all their work.',
        fingerNote: 'The index finger extension looks completely natural and isn\'t suspicious. Spectators rarely notice the difference.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Biddle Grip',
        instruction: 'Hold the deck from above: thumb on the near short edge, fingers on the far short edge. This is the grip used for the Biddle move, certain palms, and card-to-pocket routines. It\'s less common but essential for specific techniques.',
        cardAnimation: 'cut',
      },
      {
        _key: 's4',
        stepNumber: 4,
        title: 'Transitioning Between Grips',
        instruction: 'The real skill is moving between grips invisibly. Practice going from dealer\'s to mechanic\'s and back in a single motion. The transition should be imperceptible — it looks like you\'re simply adjusting your hold.',
        fingerNote: 'Transitions are covered during natural pauses in patter. Never switch grips while a spectator is watching your hands directly.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Gripping too tightly',
        fix: 'A white-knuckle grip telegraphs tension to your audience. Hold the deck firmly enough to control it, loosely enough that your hand looks relaxed.',
      },
      {
        _key: 'm2',
        mistake: 'Looking at your hands',
        fix: 'Train yourself to feel your grip, not see it. If you look at your hands, so does your audience.',
      },
    ],
    practiceDrill: {
      title: 'Grip Cycling',
      description: 'Cycle through all three grips — dealer\'s → mechanic\'s → biddle → dealer\'s — without looking at your hands, while maintaining a conversation.',
      reps: '20 cycles, eyes up the entire time',
    },
    performanceContext: 'Your grip choice should be invisible. The audience should never think about how you\'re holding the cards — they should only see confidence and ease.',
  },

  'basic-spread': {
    _id: 'demo-basic-spread',
    _type: 'lesson',
    title: 'Basic Spread',
    slug: { current: 'basic-spread' },
    category: 'foundations',
    level: 'complete-beginner',
    tagline: 'Every magician\'s first gesture. Make it beautiful.',
    overview: 'The ribbon spread — laying all 52 cards in a clean arc across a table — is often the very first thing an audience sees. Done well, it communicates mastery before you\'ve performed a single trick. It\'s also the starting position for a dozen essential moves: the card selection spread, the two-handed spread, and the spring.',
    estimatedTime: 10,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Table Position',
        instruction: 'You need a soft surface — a close-up mat, felt cloth, or even carpet. Hard surfaces make the spread uneven. Place the deck face-down near the left edge of your working area.',
        cardAnimation: 'fan',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Push',
        instruction: 'With your right index finger on top of the deck (or two fingers for better control), push the deck to the right in one smooth motion. Your finger rides along the top of the deck and pushes each card slightly forward as you move right. The goal is even, consistent pressure throughout the motion.',
        fingerNote: 'The pushing finger should feel slight resistance from each card as it deposits. If it feels like you\'re just dragging the top card, you\'re not engaging the whole deck.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Achieving the Arc',
        instruction: 'A straight line of cards looks mechanical. Slightly curve your motion as you spread — start pointing slightly toward yourself, end pointing slightly away. This creates a natural-looking arc that fills the table and looks effortlessly elegant.',
      },
      {
        _key: 's4',
        stepNumber: 4,
        title: 'The Turnover Spread',
        instruction: 'Once spread, draw your finger back across the cards from right to left, applying slight upward pressure to flip each card face-up as you pass. This is called a "ribbon turnover" — 52 cards flipping in a smooth wave. It\'s purely visual and absolutely stunning.',
        cardAnimation: 'reveal',
        fingerNote: 'The turnover flip requires that cards slightly overlap. If your spread is too sparse, cards won\'t flip in sequence.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Uneven spacing',
        fix: 'Practice on a mat and slow down. Speed comes after consistency. Each card should be evenly spaced — about 1cm of card visible per card in the fan.',
      },
      {
        _key: 'm2',
        mistake: 'Cards bunching on one side',
        fix: 'You\'re applying too much pressure at the start and releasing it at the end. Practice with consistent, even pressure throughout the full motion.',
      },
    ],
    practiceDrill: {
      title: 'The Perfect Arc',
      description: 'Spread the deck, assess the spacing, collect, and repeat. Film yourself from above to see where your spread bunches or gaps.',
      reps: '15 spreads — aiming for perfect even spacing on each',
    },
    performanceContext: 'Open with a spread when you want to establish authority immediately. It signals to the audience that you\'re not an amateur. Pair it with a calm, confident statement: "Take any card you like."',
  },

  'squaring-the-deck': {
    _id: 'demo-squaring',
    _type: 'lesson',
    title: 'Squaring the Deck',
    slug: { current: 'squaring-the-deck' },
    category: 'foundations',
    level: 'complete-beginner',
    tagline: 'The move that hides every other move.',
    overview: 'Squaring the deck appears in every single card routine — it\'s the action that conceals breaks, prepares for controls, and resets your working position. The magician who can square a deck quickly and cleanly, while maintaining a hidden break or crimp, has mastered one of the most important invisible skills in card magic.',
    estimatedTime: 8,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Basic Two-Handed Square',
        instruction: 'Hold the deck in your left hand in mechanic\'s grip. Bring your right hand to the deck, thumb at the back short edge and fingers at the front short edge. Gentle squeezing pressure from both sides aligns all cards. Simultaneously, tap the long edges on your palm to align those sides.',
        cardAnimation: 'cut',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Table Square',
        instruction: 'Place the deck face-down on the table. Bring all four sides inward with gentle taps using the pads of your fingers. This is the most visually convincing square — it looks perfectly fair because the deck never leaves the table.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Squaring With a Hidden Break',
        instruction: 'The real skill: squaring the deck while maintaining a pinky break at a specific card. Your left pinky holds the break. As your right hand squares the top portion down onto the break, your pinky reseats beneath the squared cards. The audience sees a clean square — you feel exactly where your target card is.',
        fingerNote: 'The pinky break must be completely invisible from the front. Only 1-2mm of gap is needed — enough to feel, not enough to see.',
        cardAnimation: 'shuffle',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Squaring too aggressively',
        fix: 'Hard taps make noise and draw attention. Gentle pressure is more effective and looks more natural.',
      },
      {
        _key: 'm2',
        mistake: 'Losing the break during squaring',
        fix: 'Practice the break alone first — hold it for 30 seconds while doing nothing else. Then add the squaring action only when the break feels secure.',
      },
    ],
    practiceDrill: {
      title: 'Square and Break',
      description: 'Have a friend insert a card anywhere in the deck. Without looking, maintain a break at that position while squaring the deck three times completely. Then name the position.',
      reps: '10 rounds — no peeking',
    },
    performanceContext: 'Squaring should become so automatic it disappears from your performance entirely. The audience should never be aware it\'s happening — it\'s pure infrastructure.',
  },

  'pinky-break': {
    _id: 'demo-pinky-break',
    _type: 'lesson',
    title: 'Pinky Break',
    slug: { current: 'pinky-break' },
    category: 'sleights',
    level: 'beginner',
    tagline: 'The invisible foundation. Without this, nothing else works.',
    overview: 'The pinky break is a tiny gap maintained between two portions of the deck using the tip of your left little finger. It\'s invisible to spectators but tells you exactly where in the deck any card is. Almost every card control, force, and cut uses the pinky break as its foundation.',
    estimatedTime: 20,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Getting Into the Break',
        instruction: 'Hold the deck in mechanic\'s grip. When a card is returned to the deck, your right thumb creates a tiny gap at the point of insertion. Your left pinky tip slips into this gap immediately as the right hand squares the card flush. The pinky tip rests against the right long edge of the lower packet.',
        fingerNote: 'The break is taken at the INNER right corner of the deck — the corner closest to your palm. This is where the pinky naturally rests and where it\'s least visible.',
        cardAnimation: 'cut',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'Maintaining the Break',
        instruction: 'A proper break requires virtually no effort. Your pinky tip is simply inserted — gravity and the weight of the upper packet do the work. You should be able to hold a break for several minutes without fatigue. If it hurts, you\'re gripping too hard.',
        fingerNote: 'You only need 1-2mm of gap. Beginners often take breaks of 5-10mm which are visible. Smaller is better.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'The Break During Action',
        instruction: 'The real test is maintaining the break while doing other things — talking, gesturing, even shuffling the top portion of the deck. Practice having a conversation while holding a break. You should be able to look someone in the eye and discuss the weather while your pinky holds your secret.',
        cardAnimation: 'shuffle',
      },
      {
        _key: 's4',
        stepNumber: 4,
        title: 'Converting a Break to a Control',
        instruction: 'Once you have a break, you have the power to control that card anywhere. The most basic conversion: transfer the break to your right thumb, then perform a double undercut — two cuts that bring the card to the top of the deck.',
        fingerNote: 'The break-to-control action should take under two seconds. Practice the timing until it feels like one single motion.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Taking too large a break',
        fix: 'A visible gap destroys the illusion. Less than 2mm. Feel it, don\'t see it.',
      },
      {
        _key: 'm2',
        mistake: 'Looking at your hands while holding the break',
        fix: 'If you look, your audience looks. Train with a mirror so you can see your hands without directing attention to them.',
      },
      {
        _key: 'm3',
        mistake: 'Tensing your entire hand',
        fix: 'Tension is visible. Your hand should look relaxed — only your pinky is doing any work.',
      },
    ],
    practiceDrill: {
      title: 'The Conversation Break',
      description: 'Hold a break while having a full conversation with someone. They should have no idea. Time yourself — work up to 3 minutes without losing the break or being detected.',
      reps: 'Daily, 5-minute sessions — make it part of every practice',
    },
    performanceContext: 'A pinky break is your most-used invisible tool. It should be so natural that you take one without thinking. Every card returned to the deck is an opportunity for a break.',
  },

  'double-lift': {
    _id: 'demo-double-lift',
    _type: 'lesson',
    title: 'Double Lift',
    slug: { current: 'double-lift' },
    category: 'sleights',
    level: 'intermediate',
    tagline: 'Show one card, conceal another. The most-used sleight in all of card magic.',
    overview: 'The double lift allows you to display the "top card" of the deck while actually showing the second card. You turn two cards as one. This creates a reality gap that underpins hundreds of tricks — including the Ambitious Card, card stabbings, and virtually every card-to-pocket routine. You will use this move in every single performance.',
    estimatedTime: 35,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Getting the Two-Card Break',
        instruction: 'Before the double lift, you need a break under the top two cards. Classic method: your right thumb riffles the back edge of the deck from bottom to top — stopping to allow exactly two cards to fall. Your left pinky catches a break under those two cards.',
        fingerNote: 'The riffle is performed as a casual gesture — like you\'re just thinking. Do it while looking at the spectator, not the deck.',
        cardAnimation: 'shuffle',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Turnover',
        instruction: 'With the two-card break established, your right hand comes to the deck. Thumb at the inner short edge, index finger bent on top, remaining fingers at the outer short edge. Lift both cards as one, then pivot them face-up toward you, resting the face-up double on top of the deck.',
        fingerNote: 'The cards must behave as one. Any bend, flex, or separation between the two cards kills the illusion.',
        cardAnimation: 'reveal',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Showing the Card',
        instruction: 'The double is now face-up on top of the deck, showing a card that isn\'t actually on top. Pause here. Let the audience see it. This is your moment of deception — the audience commits this "top card" to memory. Then turn it face-down as a single unit.',
        fingerNote: 'Don\'t rush this step. The longer the audience looks at the "wrong" card, the more powerful the eventual reveal.',
      },
      {
        _key: 's4',
        stepNumber: 4,
        title: 'Dealing the Real Top Card',
        instruction: 'After turning the double down, deal the actual top card (which is different from what they saw). The audience believes you\'re dealing the card they just saw. This is the core deception. Now you can cause effects that seem impossible.',
        cardAnimation: 'cut',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'The two cards separating during the turnover',
        fix: 'You need a cleaner break and lighter touch. The cards should be gripped at their long edge, not their corners.',
      },
      {
        _key: 'm2',
        mistake: 'The double "flapping" during the show',
        fix: 'Keep a light grip on both cards throughout the display. They should move as a rigid unit.',
      },
      {
        _key: 'm3',
        mistake: 'Taking too long to get the break',
        fix: 'The break should be taken in a single casual motion that looks like nothing. If you\'re visibly "working" the cards before the double, alert spectators will notice.',
      },
    ],
    practiceDrill: {
      title: 'Hundred Doubles',
      description: 'Perform 100 double lifts in a row. Focus on smooth, consistent technique every single rep. Film the last 10 to assess how natural it looks.',
      reps: '100 lifts per session, 3 sessions per week minimum',
    },
    performanceContext: 'The double lift is most powerful when the spectator is completely focused on something else — their chosen card returning to the deck, for example. The double is performed in the background while attention is directed elsewhere.',
  },

  'overhand-shuffle': {
    _id: 'demo-overhand',
    _type: 'lesson',
    title: 'Overhand Shuffle',
    slug: { current: 'overhand-shuffle' },
    category: 'shuffles',
    level: 'complete-beginner',
    tagline: 'The world\'s most common shuffle. Now learn to control it.',
    overview: 'The overhand shuffle is how most people in the world shuffle cards. It looks completely random — but in the hands of a magician, it\'s a precision control tool. You can maintain any card at the top, bottom, or any position in the deck with an overhand shuffle that looks completely fair.',
    estimatedTime: 15,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'The Basic Action',
        instruction: 'Hold the deck in your left hand, face-down, held between thumb (near side) and fingers (far side). Your right hand grabs the bottom portion of the deck and pulls it upward and over the left-hand cards. Your left thumb peels small packets off the top of the right-hand portion, dropping them onto the left-hand cards. Repeat.',
        cardAnimation: 'shuffle',
        fingerNote: 'The right hand moves in a continuous arc — up and over. Don\'t stop and start. Fluid motion looks natural.',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'Controlling the Top Card',
        instruction: 'To keep the top card on top throughout the shuffle: on your first action, your left thumb pulls just one card off the right-hand packet. Then shuffle all remaining cards on top of it. The "one card" you pulled first stays on top the entire time.',
        fingerNote: 'This "pull one, dump the rest" action should look identical to a normal shuffle. The single card drop must be as casual as any other drop.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Controlling the Bottom Card',
        instruction: 'To keep the bottom card at the bottom: shuffle normally until the last few cards remain in your right hand. Instead of dropping them onto the left-hand packet, undercut them — bring them to the bottom. The original bottom card never moves.',
        cardAnimation: 'cut',
      },
      {
        _key: 's4',
        stepNumber: 4,
        title: 'The In-Jog Control',
        instruction: 'When a spectator inserts a card, accept it with your left thumb but deliberately jog it inward about 1cm before continuing the shuffle. After one complete shuffle, you can find the jogged card by feel and cut directly to it.',
        fingerNote: 'The jog must be subtle — 1cm max. You can feel it clearly but it\'s invisible under normal conditions.',
        cardAnimation: 'shuffle',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Shuffling too slowly',
        fix: 'A slow shuffle looks deliberate. Match the rhythm of a normal, casual shuffle — which is actually quite fast.',
      },
      {
        _key: 'm2',
        mistake: 'Looking at the top card while controlling it',
        fix: 'You don\'t need to see the top card — you\'re feeling it. Look at your spectator while you shuffle.',
      },
    ],
    practiceDrill: {
      title: 'Ace Control',
      description: 'Put all four Aces on top of the deck. Overhand shuffle 10 times. All four Aces should still be on top. If they\'re not, find where they went and figure out which shuffle lost them.',
      reps: '20 rounds — pass rate target: 18/20',
    },
    performanceContext: 'The overhand shuffle is your most convincing "fair" shuffle precisely because audiences do it themselves. When you offer to let them shuffle — and then offer to shuffle once more — they believe the deck is genuinely random. It isn\'t.',
  },

  'hindu-shuffle': {
    _id: 'demo-hindu',
    _type: 'lesson',
    title: 'Hindu Shuffle',
    slug: { current: 'hindu-shuffle' },
    category: 'shuffles',
    level: 'complete-beginner',
    tagline: 'Ancient, beautiful, deceptive — and the perfect cover for a force.',
    overview: 'The Hindu shuffle is one of the oldest shuffling techniques in card magic, originating from South Asia. It\'s distinct from the overhand shuffle in its grip and action — and it enables an entirely different set of controls and forces. The Hindu force (making a spectator "choose" a predetermined card) is built directly on this shuffle.',
    estimatedTime: 15,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'The Starting Grip',
        instruction: 'Hold the deck horizontally in your right hand: thumb on the near long edge, middle and ring fingers on the far long edge. Your left hand approaches from below. Left thumb on one long edge, fingers on the other.',
        cardAnimation: 'shuffle',
        fingerNote: 'The deck is held loosely in the right hand — it needs to be able to release packets freely.',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Pull Action',
        instruction: 'Your left hand pulls small packets from the top of the deck by pinching them between thumb and fingers, letting them fall onto your left palm. Your right hand stays stationary — the left hand does all the movement, repeatedly pulling and releasing small packets.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Card Selection During Hindu',
        instruction: 'During a Hindu shuffle, you can offer a spectator a free choice: "Tell me to stop whenever you like." When they say stop, you show the bottom card of the right-hand packet (the next card that would have fallen). This looks completely free — you can control exactly which card that is.',
        cardAnimation: 'reveal',
        fingerNote: 'Position your target card at a specific location before beginning. With practice, you\'ll be able to time the shuffle to land on it consistently.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Dropping cards',
        fix: 'Loosen your right hand grip and tighten the left hand pinch. The left hand should be actively taking cards, not waiting for them to fall.',
      },
    ],
    practiceDrill: {
      title: 'Stop Timing',
      description: 'Place the Ace of Spades 15 cards from the top. Perform a Hindu shuffle. Ask a practice partner to say stop — then show them the Ace.',
      reps: '30 attempts — track your success rate',
    },
    performanceContext: 'The Hindu shuffle looks exotic and skillful to Western audiences who don\'t recognize it. It reads as "different" — which makes the force all the more convincing because it looks like a genuinely random method.',
  },

  'key-card-control': {
    _id: 'demo-key-card',
    _type: 'lesson',
    title: 'Key Card Control',
    slug: { current: 'key-card-control' },
    category: 'controls',
    level: 'beginner',
    tagline: 'The simplest and most reliable card location in existence.',
    overview: 'A key card is a card whose identity you know — placed adjacent to a spectator\'s chosen card. After any shuffle, you simply look through the deck for your key card, and their chosen card is right next to it. No sleight of hand required. This is the foundation of beginner card magic.',
    estimatedTime: 20,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Establishing Your Key Card',
        instruction: 'Before showing the deck, secretly glimpse the bottom card. This is your key card. Spread the deck face-down and ask a spectator to take any card. While they look at their card, control the deck so your key card is directly above where their card will be returned.',
        cardAnimation: 'fan',
        fingerNote: 'Glimpsing the bottom card is easy during a casual cut or square. Glance at it naturally, as if checking the deck.',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Return',
        instruction: 'Ask the spectator to place their card back in the deck. Cut the deck to show them it\'s "lost," but ensure your key card ends up directly above their card. The simplest method: have them place the card on top of the bottom half, then drop the top half on top — your key card is now directly above theirs.',
        cardAnimation: 'cut',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Finding the Card',
        instruction: 'Shuffle the deck (or hand it to them to shuffle). Then spread through the face-up deck looking for your key card. The chosen card is immediately below (or above, depending on your arrangement). You now know exactly what it is and where it is.',
        cardAnimation: 'reveal',
        fingerNote: 'Look for your key card at a natural pace — scanning the deck with apparent concentration. Don\'t rush. Build theatrical tension.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Losing the key card during a shuffle',
        fix: 'For beginners, use a cut instead of a shuffle. Overhand shuffles can scatter the key card-chosen card relationship. Once you\'ve learned overhand shuffle controls, you can maintain the key pair through shuffles.',
      },
      {
        _key: 'm2',
        mistake: 'Revealing too quickly',
        fix: 'Use the search time to build drama. Pretend to struggle before finding it. The reveal is more powerful with tension.',
      },
    ],
    practiceDrill: {
      title: 'Key Card Chain',
      description: 'Have five different people each "choose" a card. Locate all five using key cards set before each selection. Perform this as a single routine — five impossible revelations in a row.',
      reps: '10 complete run-throughs — zero errors',
    },
    performanceContext: 'Key card is your safety net. Even if another technique fails mid-performance, a secretly known key card can salvage almost any trick. Never perform without one established.',
  },

  'double-undercut': {
    _id: 'demo-double-undercut',
    _type: 'lesson',
    title: 'Double Undercut',
    slug: { current: 'double-undercut' },
    category: 'controls',
    level: 'beginner',
    tagline: 'Two cuts that secretly bring any card to the top.',
    overview: 'The double undercut uses two cuts to secretly bring a card from anywhere in the deck to the top — all while looking like a casual, fair-seeming cut. It\'s the most common method for controlling a card after a break is established. Once learned, it becomes completely automatic.',
    estimatedTime: 25,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Establish the Break',
        instruction: 'You need a pinky break above the target card. Classic scenario: a spectator returns a card to the middle of the deck, and you\'ve secured a pinky break above it.',
        cardAnimation: 'cut',
        fingerNote: 'The break is at the inner right corner — only you can feel it. From the front, the deck looks perfectly squared.',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'First Undercut',
        instruction: 'Transfer the break to your right thumb. Your right hand now holds the upper portion (above the break). Your left hand takes the lower portion and moves it to the top — a "cut" of the bottom section to the top. Now the target card is second from the top.',
        fingerNote: 'This should look like a slow, deliberate, transparent cut. That\'s exactly what makes it convincing.',
        cardAnimation: 'shuffle',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Second Undercut',
        instruction: 'Immediately take approximately half the deck from the bottom and move it to the top again. This second cut completes the control — your target card is now on top. Two cuts, card is on top, looks like a genuine fair cut.',
        cardAnimation: 'cut',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Making the cuts too equal',
        fix: 'Two perfectly equal cuts look mechanical. Vary the packet sizes on each cut to match how a casual, careless person cuts cards.',
      },
      {
        _key: 'm2',
        mistake: 'Pausing between cuts',
        fix: 'Both cuts should flow in one continuous motion. Pause = thinking = suspicion.',
      },
    ],
    practiceDrill: {
      title: 'Invisible Top',
      description: 'Perform the double undercut 50 times, then check: is your target card actually on top? After 50 reps, record yourself and watch for any telegraphing of the secret.',
      reps: '50 reps per session',
    },
    performanceContext: 'The double undercut is your go-to control when you want to "show" the spectator that you\'re cutting cards fairly. Offer to cut once — do both cuts quickly — and their card is on top.',
  },

  'classic-palm': {
    _id: 'demo-classic-palm',
    _type: 'lesson',
    title: 'Classic Palm',
    slug: { current: 'classic-palm' },
    category: 'sleights',
    level: 'advanced',
    tagline: 'Invisible concealment. The ultimate hide.',
    overview: 'Classic palm allows you to hide a playing card completely in the natural curl of your hand. When done correctly, your hand looks perfectly natural and relaxed. No one suspects you\'re holding a card. It takes months of dedicated practice, but once mastered, it opens a completely new dimension of card magic.',
    estimatedTime: 60,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Understanding the Palm Position',
        instruction: 'Relax your right hand naturally at your side. Notice the slight natural curl — your fingers aren\'t straight, and there\'s a concave space in your palm. This hollow is exactly where a playing card sits in the classic palm. The card is held by muscle tension, not finger contact.',
        fingerNote: 'The card must not touch your fingers while palmed. It rests in the palm only. If your fingers are curled around it, it will be visible.',
        cardAnimation: 'reveal',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'Getting the Card Into Palm',
        instruction: 'With the target card on top of the deck, your right hand approaches in a grip position. As your fingers contact the card, the heel of your palm pushes the card back while your fingers pull the deck away. The card pops into palm position. This steal happens in a fraction of a second.',
        cardAnimation: 'cut',
        fingerNote: 'The motion must look identical to simply picking up the deck. The steal happens in the moment of contact — no hesitation.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Natural Hand Position While Palming',
        instruction: 'The test: stand in front of a mirror with a card palmed. Let your arm hang at your side. Can you see the card? Your hand should look completely natural. If you can see the edge of the card, your palm is too flat or your fingers too straight.',
      },
      {
        _key: 's4',
        stepNumber: 4,
        title: 'Disposing of the Palmed Card',
        instruction: 'The hardest part: getting the card out of palm without detection. Classic method — bring your hand back to the deck and push the palmed card onto the top in the same motion. Takes time to make look natural.',
        cardAnimation: 'shuffle',
        fingerNote: 'Never dispose of a palmed card while someone is watching your hand. Misdirect their attention first.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Holding the palm too tightly',
        fix: 'The card should be held by minimal tension. If your hand looks tense, reduce the grip pressure.',
      },
      {
        _key: 'm2',
        mistake: 'Rushing the steal',
        fix: 'Paradoxically, the steal works better with slower, more deliberate hand movement — quicker movements create more visual disturbance.',
      },
    ],
    practiceDrill: {
      title: 'The Natural Walk',
      description: 'Palm a card. Walk across the room. Have a conversation. Gesture with your other hand. Your right hand should never draw attention.',
      reps: 'Daily 10-minute sessions — become comfortable with the card palmed',
    },
    performanceContext: 'Classic palm enables card-to-pocket, card-to-wallet, and card-across routines. These are among the most powerful effects in card magic because they cause a card to appear somewhere it has no right to be.',
  },

  'misdirection': {
    _id: 'demo-misdirection',
    _type: 'lesson',
    title: 'Misdirection',
    slug: { current: 'misdirection' },
    category: 'foundations',
    level: 'professional',
    tagline: 'Control every eye in the room. The invisible master skill.',
    overview: 'Misdirection is not about distraction — it\'s about attention management. A master magician doesn\'t hide things from their audience; they decide exactly what the audience sees and when. This is the skill that separates performers who fool people from performers who create genuine wonder.',
    estimatedTime: 45,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'The Eye Leads the Hand',
        instruction: 'Where you look, your audience looks. This is the most fundamental principle of misdirection. When you want to conceal a move, look away from your hands. When you want to direct attention to your hands, look at them. Your gaze is a spotlight.',
        cardAnimation: 'none',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'Contrast and Motion',
        instruction: 'The eye is drawn to movement and contrast. When you want to conceal action in one hand, create movement with the other. The audience\'s visual system automatically tracks the larger, more dramatic motion.',
        fingerNote: 'A small, slow movement in the secret hand combined with a large, fast movement in the other is invisible.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'Timing and Naturalness',
        instruction: 'The perfect moment to make a secret move is the moment before the audience expects to see anything. If you cause an action, then make your secret move — instead of making your move during the action — you\'re working against the audience\'s attention. Misdirection must be woven into the patter and performance, not bolted on.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Using obvious misdirection',
        fix: '"Look over there!" is not misdirection — it\'s suspicion. The best misdirection arises naturally from the performance. A question, a revelation, an emotional moment all direct attention without any effort.',
      },
    ],
    practiceDrill: {
      title: 'The Invisible Transfer',
      description: 'Practice moving a small object from one hand to the other while looking directly at someone and asking them a question. The question is your misdirection — the answer demands their eye contact and mental attention simultaneously.',
      reps: '20 minutes daily for 30 days',
    },
    performanceContext: 'Every secret move you know requires misdirection to be effective. Misdirection isn\'t something you add to your technique — it is the technique.',
  },

  'erdnase-colour-change': {
    _id: 'demo-erdnase',
    _type: 'lesson',
    title: 'Erdnase Colour Change',
    slug: { current: 'erdnase-colour-change' },
    category: 'sleights',
    level: 'advanced',
    tagline: 'One brush of the hand. One card becomes another. Pure visual magic.',
    overview: 'Devised by S.W. Erdnase in his 1902 masterwork "The Expert at the Card Table," this colour change has never been surpassed. A card on top of the deck visually transforms into a completely different card in a single sweeping motion. The visual impact is breathtaking — audiences consistently gasp.',
    estimatedTime: 50,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'The Setup',
        instruction: 'Your target card (the card that will "appear") is second from the top. The top card is the "display" card — what the audience sees before the change. Establish a pinky break between the top two cards.',
        cardAnimation: 'reveal',
        fingerNote: 'Casually display the top card before the change. The audience needs to "register" it — give them a clear look.',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Sweep',
        instruction: 'Bring your right hand across the top of the deck from right to left in a smooth brushing motion. As your right hand covers the deck, your left thumb pushes the second card to the right, while your right palm secretly takes the first card away. Your right hand continues its sweep and clears — leaving the second card face-up on top.',
        fingerNote: 'The sweep should look completely unrelated to the card change. It should look like a gesture — like you\'re fanning away smoke.',
        cardAnimation: 'shuffle',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'The Speed',
        instruction: 'The change happens during the sweep — not before it, not after it. The timing must be exact. Too early and the audience sees two cards. Too late and they see you fumbling. The cards change at the exact moment your palm covers them.',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Watching your own hands',
        fix: 'Look at your spectator\'s face during the change. Their reaction tells you it worked. Watching your hands draws everyone\'s eye to the exact moment you don\'t want them watching.',
      },
      {
        _key: 'm2',
        mistake: 'Making the sweep too deliberate',
        fix: 'The sweep should look like a thoughtless gesture. The less purposeful it looks, the more impossible the change seems.',
      },
    ],
    practiceDrill: {
      title: 'Mirror Work',
      description: 'Perform the Erdnase change in front of a mirror, eyes on your own eyes — not your hands. If you can see the switch, so can they. Keep practicing until the mirror shows only magic.',
      reps: '60 reps per session, mirror only',
    },
    performanceContext: 'Use the Erdnase as a punctuation mark in a routine — a single visual exclamation that caps a sequence. It\'s too powerful to use casually. Save it for the moment when you want the room to gasp.',
  },

  'hindu-force': {
    _id: 'demo-hindu-force',
    _type: 'lesson',
    title: 'Hindu Force',
    slug: { current: 'hindu-force' },
    category: 'controls',
    level: 'intermediate',
    tagline: 'Free choice? That\'s what they think.',
    overview: 'The Hindu force uses the rhythm of the Hindu shuffle to force a specific card onto a spectator. They believe they stopped you freely — in reality, you\'ve predetermined exactly which card they\'ll see. It\'s the cleanest, most natural-feeling force in card magic.',
    estimatedTime: 30,
    steps: [
      {
        _key: 's1',
        stepNumber: 1,
        title: 'Positioning the Force Card',
        instruction: 'Your force card must be on top of the deck before you begin. Establish this secretly before approaching your audience — during a previous trick, a casual cut, or a false shuffle.',
        cardAnimation: 'cut',
        fingerNote: 'The force card on top is completely hidden. The audience sees only the back of the top card during the shuffle.',
      },
      {
        _key: 's2',
        stepNumber: 2,
        title: 'The Shuffle and the Stop',
        instruction: 'Begin a Hindu shuffle. Ask the spectator to say "stop" whenever they like. As they say stop, you freeze — showing them the bottom card of the right-hand packet. But here\'s the key: no matter when they say stop, you ensure the force card is the one shown. You control the timing of the shuffle to coincide with their stop.',
        cardAnimation: 'shuffle',
        fingerNote: 'You have more control than you think. If they say stop too early, continue for one more pull of cards before "registering" the stop. The hesitation is invisible.',
      },
      {
        _key: 's3',
        stepNumber: 3,
        title: 'The Grace Period',
        instruction: 'You have approximately a half-second grace period between when the spectator says stop and when you actually stop. This is enough time to complete one more pull if needed. Practice feeling this timing — it\'s the heart of the force.',
        cardAnimation: 'reveal',
      },
    ],
    commonMistakes: [
      {
        _key: 'm1',
        mistake: 'Forcing too mechanically',
        fix: 'If you stop at exactly the same point every time, a sharp observer will notice the pattern. Vary your shuffle rhythm and stopping point while always landing on the force card.',
      },
    ],
    practiceDrill: {
      title: 'Ten-Person Force',
      description: 'Force the Ace of Spades on ten different people in a row, letting each of them say stop freely. Perfect score is 10/10. Below 8/10, keep practicing the timing.',
      reps: '10-person sessions until you hit 10/10 three times running',
    },
    performanceContext: 'The Hindu force works best when you appear casual about it — like you genuinely don\'t care when they stop. Nonchalance is your strongest weapon. The more indifferent you seem, the freer their choice appears.',
  },
}
